[package]
name = "backend"
version = "0.1.0"
authors = ["Mark Barbone <mark.l.barbone@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
rocket = {version = "0.4.4", features = ["tls"]}
tiny_http = "0.6"
